db.url=jdbc:mysql://localhost:3306/students_db?createDatabaseIfNotExist=true
db.username=root
db.password=
db.pool.size=10

# Gmail SMTP Settings
mail.host=smtp.gmail.com
mail.port=587
mail.username=worldcraft223@gmail.com
mail.password=ugfjkhcndrvfavzm
mail.from=worldcraft223@gmail.com
